---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://34.89.137.89:8200" # Calling local vault running in same cluster
      path: "argocd"
      version: "v2"
      auth:
        appRole:
          tokenSecretRef:
            name: "vault-token"
            key: "token"
            namespace: external-secrets # namespace where you can find the secret id for given app role
---
apiVersion: v1
kind: Secret
metadata:
  name: "vault-token"
data:
  token: "cy5PbGlVUm9DQWk4V3d5WVkzd3pWTUFLdW8=" 